logging:
  level:
    be.nexios.project: debug

spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: nexios
      authentication-database: admin